services: 
  mariadb:
    build: ./mariadb
    container_name: culturallm-db
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb/data/:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: culturallm_db

  backend:
    build: ./backend
    container_name: culturallm-backend
    ports: 
      - "8003:8003"
    depends_on: 
      mariadb:
        condition: service_healthy
    environment:
      DB_HOST: culturallm-db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: culturallm_db
