services: 
    mariadb:
        image: mariadb:11.7.2-ubi9
        container_name: database-culturallm
        ports:
          - "3307:3306"
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: culturallm_db
          MYSQL_USER: backend
          MYSQL_PASSWORD: backend1234
        volumes:
          - ./mariadb_data/:/var/lib/mysql:Z
          - ./mariadb_init/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          start_period: 5s
          interval: 5s
          timeout: 5s
          retries: 3
    backend:
        build: ./backend
        ports: 
        - "8003:8003"
        container_name: backend-culturallm
        depends_on: 
          mariadb:
            condition: service_healthy

